apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../infra/openshift-pipelines
  - ../../infra/tenant-config

patches:
  - path: patch-applicationset.yaml
    target:
      kind: ApplicationSet
      name: tenant-config
