apiVersion: v1
kind: ConfigMap
metadata:
  name: feature-flags
data:
  running-in-environment-with-injected-sidecars: 'true'
  await-sidecar-readiness: 'true'
  require-git-ssh-secret-known-hosts: 'false'
  enable-tekton-oci-bundles: 'false'
  send-cloudevents-for-runs: 'false'
  embedded-status: full
  enable-api-fields: stable
  enable-custom-tasks: 'false'
  disable-creds-init: 'false'
  disable-affinity-assistant: 'true'
