apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../infra/cluster-gitops

patches:
  - path: patch-applicationset.yaml
    target:
      kind: ApplicationSet
      name: cluster-config
