apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../infra/cluster-gitops
patches:
  - path: patch-cluster-config.yaml
    target:
      kind: ApplicationSet
      name: cluster-config
